name: 'Composite action for jamstack'
inputs:
  inputs:
  action:
    description: "Action to perform"
    required: true
  app_location:
    description: "Directory location of the application source code"
    required: true
  azure_static_web_apps_api_token:
    description: "Required token"
    required: true
  api_build_command:
    description: "Custom command for Oryx to run when building Azure Functions source code"
    required: false
  api_location:
    description: "Directory location of the Azure Functions source code"
    required: false
  app_artifact_location:
    description: "Identical in use to output_location"
    required: false
  output_location:
    description: "Directory location of the compiled application code after building"
    required: false
  app_build_command:
    description: "Custom command for Oryx to run when building application source code"
    required: false
  repo_token:
    description: "Token for interacting with the Github repository. Currently used only for commenting on Pull Requests."
    required: false
  routes_location:
    description: "Directory location where the routes.json file can be found in the source code"
    required: false
  skip_app_build:
    description: "Skips the build step for the application source code if set to true."
    required: false
  config_file_location:
    description: "Directory location where the staticwebapp.config.json file can be found in the source code"
    required: false
  skip_api_build:
    description: "Skips the build step for the Azure Functions source code if set to true."
    required: false
  production_branch:
    description: "When specified, deployments from other branches will be considered preview environments."
    required: false
  deployment_environment:
    description: "Name of the Azure Static Web Apps environment to deploy to."
    required: false
  is_static_export:
    description: "Indicates you are using `next export` to generate a static site if set to true."
    required: false
outputs:
  static_web_app_url:
    description: "Url of the application"   
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v3     
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
           '~/.npm'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm3-
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VERBOSE: true
        with:
          azure_static_web_apps_api_token: ${{ inputs.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_RIVER_079E00410 }}
          repo_token: ${{ inputs.GITHUB_TOKEN }} 
          action: ${{ inputs.action }}
          app_location: ${{ inputs.app_location }}
          api_location: ${{ inputs.api_location }}
          output_location: ${{ inputs.output_location }}